import { useState } from 'react'
import type { EventType, TimelineEvent } from '../types'
import { eventMeta } from '../lib/timeline'
import { Button, Card, Field } from './ui'
import { Plus } from 'lucide-react'
export function EventForm({ onAdd, compact = false }: { onAdd: (e: Omit<TimelineEvent, 'id'>) => void; compact?: boolean }) {
  const [type, setType] = useState<EventType>('prepayment'); const [date, setDate] = useState('2026-01-01'); const [amount, setAmount] = useState('200000'); const [rate, setRate] = useState('7.95'); const [strategy, setStrategy] = useState<'reduce-tenure' | 'reduce-emi'>('reduce-tenure')
  const needsAmount = type !== 'rate-change'; const submit = () => onAdd({ type, date, amount: needsAmount ? Number(amount) : undefined, rate: type === 'rate-change' ? Number(rate) : undefined, strategy: type === 'prepayment' ? strategy : undefined })
  return <Card className={compact ? 'p-4' : 'p-5'}><div className="mb-4 flex items-center gap-2"><div className="rounded-lg bg-mint/10 p-2 text-mint"><Plus size={16}/></div><div><h3 className="text-sm font-bold">{compact ? 'Try a what-if' : 'Add timeline event'}</h3><p className="text-xs text-slate-500">Changes recalculate the complete schedule.</p></div></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium text-slate-500"><span className="mb-1.5 block">Event type</span><select value={type} onChange={e => setType(e.target.value as EventType)} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none dark:border-white/10 dark:bg-slate-950 dark:text-white">{Object.entries(eventMeta).map(([key, e]) => <option key={key} value={key}>{e.label}</option>)}</select></label><Field label="Effective date" type="date" value={date} onChange={e => setDate(e.target.value)} />{needsAmount ? <Field label="Amount (₹)" type="number" min="0" value={amount} onChange={e => setAmount(e.target.value)} /> : <Field label="New annual rate (%)" type="number" min="0" step="0.05" value={rate} onChange={e => setRate(e.target.value)} />}{type === 'prepayment' && <label className="text-xs font-medium text-slate-500"><span className="mb-1.5 block">After payment</span><select value={strategy} onChange={e => setStrategy(e.target.value as typeof strategy)} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none dark:border-white/10 dark:bg-slate-950 dark:text-white"><option value="reduce-tenure">Reduce tenure</option><option value="reduce-emi">Reduce EMI</option></select></label>}</div><Button onClick={submit} className="mt-4 w-full bg-navy text-white hover:bg-slate-700 dark:bg-mint dark:text-navy">Add event</Button></Card>
}
